version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: postgredb
    environment:
      POSTGRES_USER: emo4ka
      POSTGRES_PASSWORD: love666
      POSTGRES_DB: restapi
    volumes:
      - ./postgres:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  postgres_data:
    driver: local
